### ISSUE TITLE
Not working with Python 3.7

### ISSUE THREAD

**Issue by vicky5124** [MitchWeaver/Discline#39]
Im using Arch Linux and i need python 3.7 for some stuff that don't work on on 3.6, so i can't change version. When trying to run Discline.py i first got an async error that i fixed with [this](https://github.com/Rapptz/discord.py/issues/1249) post for discord.py, but now i have a new error that i can't seem to fix:

```
Traceback (most recent call last):
  File "Discline.py", line 211, in <module>
    if __name__ == "__main__": main()
  File "Discline.py", line 200, in main
    try: gc.client.run(token, bot=False)
  File "/usr/lib/python3.7/site-packages/discord/client.py", line 518, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/site-packages/discord/client.py", line 490, in start
    yield from self.connect()
  File "/usr/lib/python3.7/site-packages/discord/client.py", line 448, in connect
    yield from self.ws.poll_event()
  File "/usr/lib/python3.7/site-packages/discord/gateway.py", line 425, in poll_event
    msg = yield from self.recv()
  File "/usr/lib/python3.7/site-packages/websockets/protocol.py", line 434, in recv
    yield from self.ensure_open()
  File "/usr/lib/python3.7/site-packages/websockets/protocol.py", line 655, in ensure_open
    yield from asyncio.shield(self.close_connection_task)
  File "/usr/lib/python3.7/site-packages/discord/gateway.py", line 517, in close_connection
    yield from super().close_connection(force=force)
TypeError: close_connection() got an unexpected keyword argument 'force'
```
I know that it's a python 3.7 issue, because i tried it on ubuntu, where i have 3.6 and it works just fine.

**Comment by Danct12** [comment]
Use this instead, it is a fork of Discline that uses ncurses and supports Python 3.7.
https://github.com/NatTupper/dline
