### ISSUE TITLE
Problem while setup

### ISSUE THREAD

**Issue by krinistof** [MitchWeaver/Discline#28]
#python3 Discline.py --store-token
	Traceback (most recent call last):
	  File Discline.py, line 15, in <module>
	    from discord import ChannelType
	ImportError: cannot import name 'ChannelType

**Comment by Aioxas** [comment]
could you somehow show the output of `pip3 freeze`? Would like to know something

**Comment by q-TheDog** [comment]
I just tried installing and am now getting a similar error on this step:

Traceback (most recent call last):
  File "Discline.py", line 15, in <module>
    from discord import ChannelType
  File "/usr/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/usr/lib/python3.7/site-packages/discord/client.py", line 38, in <module>
    from .state import ConnectionState
  File "/usr/lib/python3.7/site-packages/discord/state.py", line 36, in <module>
    from . import utils, compat
  File "/usr/lib/python3.7/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                              ^

My pip3 freeze is here in case it helps: https://pastebin.com/0K88KCh4

**Comment by 9viz** [comment]
discord.py doesn't support python 3.7, which means Discline cannot work in python 3.7.
Downgrade to python 3.6

**Comment by mgarbvs** [comment]
I am experiencing the same error. How would one go about downgrading python completely? I am on arch.

**Comment by runarsf** [comment]
@mgarbvs Install the `python36` package from AUR (e.g. `yay -S python36`), then run python with `python3.6 [args]`

To get pip3.6:
```bash
wget https://bootstrap.pypa.io/get-pip.py
sudo python3.6 get-pip.py
# now install pip packages with
python3.6 -m pip install [package]
# or
pip3.6 install [package]
```

**Comment by zaxcer** [comment]
@runarsf i use conda and get following error on StoreToken

```
(discord_env) lgr@lgr-GT60:~/Discline$ conda install python=3.6.0
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/lgr/anaconda3/envs/discord_env:

The following packages will be DOWNGRADED:

    openssl:  1.1.1b-h7b6447c_1 --> 1.0.2r-h7b6447c_0
    python:   3.6.8-h0371630_0  --> 3.6.0-0          
    readline: 7.0-h7b6447c_5    --> 6.2-2            
    sqlite:   3.28.0-h7b6447c_0 --> 3.13.0-0         
    tk:       8.6.8-hbc83047_0  --> 8.5.18-0         

Proceed ([y]/n)? y

readline-6.2-2 100% |########################################################| Time: 0:00:00   2.39 MB/s
sqlite-3.13.0- 100% |########################################################| Time: 0:00:01   3.62 MB/s
tk-8.5.18-0.ta 100% |########################################################| Time: 0:00:00   3.39 MB/s
openssl-1.0.2r 100% |########################################################| Time: 0:00:01   3.03 MB/s
python-3.6.0-0 100% |########################################################| Time: 0:00:05   3.05 MB/s

(discord_env) lgr@lgr-GT60:~/Discline$ python3 --version
Python 3.6.0 :: Continuum Analytics, Inc.

(discord_env) lgr@lgr-GT60:~/Discline$ python3 Discline.py --store-token
Traceback (most recent call last):
  File "Discline.py", line 15, in <module>
    from discord import ChannelType
ModuleNotFoundError: No module named 'discord'
```
