### ISSUE TITLE
wont load

### ISSUE THREAD

**Issue by RusticMaple** [MitchWeaver/Discline#59]
Log: 

> `Checking for updates...
> Already up to date!
> 
> Starting...
> Ignoring exception in on_ready
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/discord/client.py", line 255, in _run_event
>     await coro(*args, **kwargs)
>   File "Discline.py", line 50, in on_ready
>     await gc.client.wait_until_login()
> AttributeError: 'Client' object has no attribute 'wait_until_login'`

**Comment by RusticMaple** [comment]
i fixed the error by making it wait for 1 minute instead of waiting for it to login
but now i get a different error: 


```

> Ignoring exception in on_ready
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/discord/client.py", line 255, in _run_event
>     await coro(*args, **kwargs)
>   File "Discline.py", line 82, in on_ready
>     for server in gc.client.servers:
> AttributeError: 'Client' object has no attribute 'servers'
> /home/tv/Desktop/dc-trm/Discline/utils/globals.py:36: RuntimeWarning: coroutine 'Client.close' was never awaited
>   try: gc.client.close()
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> 

```

**Comment by 9viz** [comment]
Python changed the async syntax in 3.7 so discline doesn't work with py3.7

Take a look at these clients though:
https://gitlab.com/diamondburned/6cord

https://github.com/nattupper/dline
